// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthUser struct {
	UserID uint64 `json:"user_id"`
}

type ChangePasswordReq struct {
	Code        string `json:"code"`
	NewPassword string `json:"new_password"`
}

type CreateExpenseCategoryReq struct {
	Name string `json:"name"`
}

type CreateExpenseLogReq struct {
	CategoryID uint64  `json:"category_id"`
	Amount     int64   `json:"amount"` // 单位：分
	Note       *string `json:"note,optional"`
	OccurredAt string  `json:"occurred_at"`
}

type CreateLifeLogReq struct {
	Content    string    `json:"content"`
	Tags       []TagInfo `json:"tags,optional"`
	OccurredAt string    `json:"occurred_at"`
}

type CreateSummaryReq struct {
	PeriodType        uint8     `json:"period_type"`
	PeriodStart       string    `json:"period_start"`
	PeriodEnd         string    `json:"period_end"`
	SummaryContent    string    `json:"summary_content"`
	SuggestionContent string    `json:"suggestion_content,optional"`
	Title             string    `json:"title,optional"`
	Tags              []TagInfo `json:"tags,optional"`
}

type DeleteExpenseCategoryReq struct {
	ID uint64 `json:"id"`
}

type DeleteExpenseLogReq struct {
	ID uint64 `json:"id"`
}

type DeleteLifeLogReq struct {
	ID uint64 `json:"id"`
}

type DeleteSummaryReq struct {
	ID uint64 `json:"id"`
}

type ExpenseByDateReq struct {
	Date string `form:"date"` // "2006-01-02"
}

type ExpenseByDateResp struct {
	List  []ExpenseLogInfo `json:"list"`
	Total int64            `json:"total"`
}

type ExpenseCategoryInfo struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
	Type uint8  `json:"type"` // 1=系统默认, 2=用户自定义
}

type ExpenseCategoryStat struct {
	CategoryID   uint64 `json:"category_id"`
	CategoryName string `json:"category_name"`
	Total        int64  `json:"total"` // 单位：分
}

type ExpenseLogInfo struct {
	ID         uint64              `json:"id"`
	Category   ExpenseCategoryInfo `json:"category"`
	Amount     int64               `json:"amount"` // 单位：分
	Note       string              `json:"note"`
	Location   string              `json:"location,optional"`
	OccurredAt string              `json:"occurred_at"`
	CreatedAt  string              `json:"created_at"`
}

type ExpenseMonthlyTrendResp struct {
	Points []MonthTotal `json:"points"`
}

type ExpenseStatsCategoryResp struct {
	Categories []ExpenseCategoryStat `json:"categories"`
}

type ExpenseStatsRangeResp struct {
	Total int64 `json:"total"` // 单位：分
}

type ExpenseStatsReq struct {
	Start string `form:"start"` // "2006-01-02"
	End   string `form:"end"`   // "2006-01-02"
}

type ExpenseStatsTrendResp struct {
	Points []ExpenseTrendPoint `json:"points"`
}

type ExpenseTrendPoint struct {
	Date  string `json:"date"`
	Total int64  `json:"total"` // 单位：分
}

type GenerateAISummaryReq struct {
	PeriodType  uint8  `json:"period_type"`  // 1=日报, 2=周报, 3=月报, 4=年报, 5=人生总结
	PeriodStart string `json:"period_start"` // 周期起始日期，统一使用 YYYY-MM-DD
}

type IDResponse struct {
	ID uint64 `json:"id"`
}

type IPLocation struct {
	IP       string `json:"ip"`
	Country  string `json:"country"`
	Province string `json:"province"`
	City     string `json:"city"`
	ISP      string `json:"isp"`
	ISOCode  string `json:"iso_code"`
}

type LifeLogByDateReq struct {
	Date string `form:"date"` // "2006-01-02"
}

type LifeLogByDateResp struct {
	List []LifeLogInfo `json:"list"`
}

type LifeLogInfo struct {
	ID         uint64    `json:"id"`
	Content    string    `json:"content"`
	Tags       []TagInfo `json:"tags,optional"`
	OccurredAt string    `json:"occurred_at"`
	CreatedAt  string    `json:"created_at"`
	UpdatedAt  string    `json:"updated_at"`
}

type ListExpenseCategoryResp struct {
	Categories []ExpenseCategoryInfo `json:"categories"`
}

type ListExpenseLogReq struct {
	PageSize  uint32 `form:"page_size"`
	PageToken string `form:"page_token,optional"`
}

type ListExpenseLogResp struct {
	List      []ExpenseLogInfo `json:"list"`
	PageToken string           `json:"page_token"`
	HasMore   bool             `json:"has_more"`
}

type ListLifeLogReq struct {
	PageSize  uint32 `form:"page_size"`
	PageToken string `form:"page_token,optional"`
	Date      string `form:"date,optional"`
	TagID     uint64 `form:"tag_id,optional"`
}

type ListLifeLogResp struct {
	List      []LifeLogInfo `json:"list"`
	PageToken string        `json:"page_token"`
	HasMore   bool          `json:"has_more"`
}

type ListSummaryReq struct {
	PeriodType uint8  `form:"period_type,optional"`
	PageSize   uint32 `form:"page_size"`
	PageToken  string `form:"page_token,optional"`
}

type ListSummaryResp struct {
	List      []SummaryInfo `json:"list"`
	PageToken string        `json:"page_token"`
	HasMore   bool          `json:"has_more"`
}

type LoginReq struct {
	Target   string `json:"target"`
	Channel  int32  `json:"channel"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string   `json:"token"`
	RefreshToken string   `json:"refresh_token"`
	UserInfo     UserInfo `json:"user_info"`
}

type MonthTotal struct {
	Month string `json:"month"`
	Total int64  `json:"total"` // 单位：分
}

type PageToken struct {
	ID        uint64 `json:"id"`
	CreatedAt string `json:"created_at"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Target   string `json:"target"`
	Channel  int32  `json:"channel"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type Response struct {
}

type SendVerificationCodeReq struct {
	Target  string `json:"target"`
	Channel int32  `json:"channel"` // 1: email
	Purpose int32  `json:"purpose"` // 1: registration, 2: password reset
}

type SummaryInfo struct {
	ID                uint64    `json:"id"`
	PeriodType        uint8     `json:"period_type"`  // 1=日报, 2=周报, 3=月报, 4=年报, 5=人生总结
	PeriodStart       string    `json:"period_start"` // 周期起始日期，统一使用 YYYY-MM-DD
	PeriodEnd         string    `json:"period_end"`   // 周期结束日期（开区间），统一使用 YYYY-MM-DD
	Source            uint8     `json:"source"`       // 1=AI, 2=用户
	SummaryContent    string    `json:"summary_content"`
	SuggestionContent string    `json:"suggestion_content,optional"`
	Title             string    `json:"title,optional"`
	Tags              []TagInfo `json:"tags,optional"`
	Location          string    `json:"location,optional"`
	CreatedAt         string    `json:"created_at"`
	UpdatedAt         string    `json:"updated_at"`
}

type SummaryRangeReq struct {
	PeriodType uint8  `form:"period_type,optional"`
	Start      string `form:"start"`
	End        string `form:"end"`
}

type SummaryRangeResp struct {
	List []SummaryInfo `json:"list"`
}

type TagInfo struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type UpdateExpenseLogReq struct {
	ID         uint64  `json:"id"`
	CategoryID uint64  `json:"category_id,optional"`
	Amount     int64   `json:"amount,optional"` // 单位：分
	Note       *string `json:"note,optional"`
	OccurredAt string  `json:"occurred_at,optional"`
}

type UpdateLifeLogReq struct {
	ID         uint64    `json:"id"`
	Content    string    `json:"content,optional"`
	Tags       []TagInfo `json:"tags,optional"`
	OccurredAt string    `json:"occurred_at,optional"`
}

type UpdateSummaryReq struct {
	ID                uint64    `json:"id"`
	SummaryContent    string    `json:"summary_content,optional"`
	SuggestionContent string    `json:"suggestion_content,optional"`
	Title             string    `json:"title,optional"`
	Tags              []TagInfo `json:"tags,optional"`
}

type UpdateUserInfoReq struct {
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserInfo struct {
	UserID    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"created_at"`
}
