// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthUser struct {
	UserID uint64 `json:"user_id"`
}

type ChangePasswordReq struct {
	Code        string `json:"code"`
	NewPassword string `json:"new_password"`
}

type IDResponse struct {
	ID uint64 `json:"id"`
}

type IPLocation struct {
	IP       string `json:"ip"`
	Country  string `json:"country"`
	Province string `json:"province"`
	City     string `json:"city"`
	ISP      string `json:"isp"`
	ISOCode  string `json:"iso_code"`
}

type LoginReq struct {
	Target   string `json:"target"`
	Channel  int32  `json:"channel"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string   `json:"token"`
	RefreshToken string   `json:"refresh_token"`
	UserInfo     UserInfo `json:"user_info"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Target   string `json:"target"`
	Channel  int32  `json:"channel"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type Response struct {
}

type SendVerificationCodeReq struct {
	Target  string `json:"target"`
	Channel int32  `json:"channel"` // 1: email
	Purpose int32  `json:"purpose"` // 1: registration, 2: password reset
}

type UpdateUserInfoReq struct {
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserInfo struct {
	UserID    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"created_at"`
}
