// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthUser struct {
	UserID uint64 `json:"user_id"`
}

type ChangePasswordReq struct {
	Code        string `json:"code"`
	NewPassword string `json:"new_password"`
}

type CreateExpenseCategoryReq struct {
	Name string `json:"name"`
}

type CreateExpenseLogReq struct {
	CategoryID uint64  `json:"category_id"`
	Amount     float64 `json:"amount"`
	Note       string  `json:"note,optional"`
	OccurredAt string  `json:"occurred_at"`
}

type CreateSummaryReq struct {
	PeriodType        uint8  `json:"period_type"`
	PeriodStart       string `json:"period_start"`
	PeriodEnd         string `json:"period_end"`
	SummaryContent    string `json:"summary_content"`
	SuggestionContent string `json:"suggestion_content,optional"`
}

type DailyExpenseTotalReq struct {
	Date string `form:"date"` // "2006-01-02"
}

type DailyExpenseTotalResp struct {
	Date  string  `json:"date"`
	Total float64 `json:"total"`
}

type DeleteExpenseCategoryReq struct {
	ID uint64 `json:"id"`
}

type DeleteExpenseLogReq struct {
	ID uint64 `json:"id"`
}

type DeleteSummaryReq struct {
	ID uint64 `json:"id"`
}

type ExpenseCategoryInfo struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
	Type uint8  `json:"type"` // 1=系统默认, 2=用户自定义
}

type ExpenseLogInfo struct {
	ID         uint64              `json:"id"`
	Category   ExpenseCategoryInfo `json:"category"`
	Amount     float64             `json:"amount"`
	Note       string              `json:"note"`
	Location   string              `json:"location,optional"`
	OccurredAt string              `json:"occurred_at"`
	CreatedAt  string              `json:"created_at"`
}

type GenerateAISummaryReq struct {
	PeriodType  uint8  `json:"period_type"`  // 1=日报, 2=周报, 3=月报, 4=年报
	PeriodStart string `json:"period_start"` // 指定周期的起始日期
}

type IDResponse struct {
	ID uint64 `json:"id"`
}

type IPLocation struct {
	IP       string `json:"ip"`
	Country  string `json:"country"`
	Province string `json:"province"`
	City     string `json:"city"`
	ISP      string `json:"isp"`
	ISOCode  string `json:"iso_code"`
}

type ListExpenseCategoryResp struct {
	Categories []ExpenseCategoryInfo `json:"categories"`
}

type ListExpenseLogReq struct {
	PageSize  uint32 `form:"page_size"`
	PageToken string `form:"page_token,optional"`
}

type ListExpenseLogResp struct {
	List      []ExpenseLogInfo `json:"list"`
	PageToken string           `json:"page_token"`
	HasMore   bool             `json:"has_more"`
}

type ListSummaryReq struct {
	PeriodType uint8  `form:"period_type,optional"`
	PageSize   uint32 `form:"page_size"`
	PageToken  string `form:"page_token,optional"`
}

type ListSummaryResp struct {
	List      []SummaryInfo `json:"list"`
	PageToken string        `json:"page_token"`
	HasMore   bool          `json:"has_more"`
}

type LoginReq struct {
	Target   string `json:"target"`
	Channel  int32  `json:"channel"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string   `json:"token"`
	RefreshToken string   `json:"refresh_token"`
	UserInfo     UserInfo `json:"user_info"`
}

type PageToken struct {
	ID        uint64 `json:"id"`
	CreatedAt string `json:"created_at"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Target   string `json:"target"`
	Channel  int32  `json:"channel"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type Response struct {
}

type SendVerificationCodeReq struct {
	Target  string `json:"target"`
	Channel int32  `json:"channel"` // 1: email
	Purpose int32  `json:"purpose"` // 1: registration, 2: password reset
}

type SummaryInfo struct {
	ID                uint64 `json:"id"`
	PeriodType        uint8  `json:"period_type"`  // 1=日报, 2=周报, 3=月报, 4=年报
	PeriodStart       string `json:"period_start"` // "2006-01-02" / "2006-W01" / "2006-01" / "2006"
	PeriodEnd         string `json:"period_end"`
	Source            uint8  `json:"source"` // 1=AI, 2=用户
	SummaryContent    string `json:"summary_content"`
	SuggestionContent string `json:"suggestion_content,optional"`
	Location          string `json:"location,optional"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type UpdateSummaryReq struct {
	ID                uint64 `json:"id"`
	SummaryContent    string `json:"summary_content,optional"`
	SuggestionContent string `json:"suggestion_content,optional"`
}

type UpdateUserInfoReq struct {
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserInfo struct {
	UserID    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"created_at"`
}
