// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/luyb177/life-tracker/backend/internal/handler/auth"
	expense "github.com/luyb177/life-tracker/backend/internal/handler/expense"
	lifelog "github.com/luyb177/life-tracker/backend/internal/handler/lifelog"
	summary "github.com/luyb177/life-tracker/backend/internal/handler/summary"
	user "github.com/luyb177/life-tracker/backend/internal/handler/user"
	"github.com/luyb177/life-tracker/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 登录账号
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// 刷新令牌
					Method:  http.MethodPost,
					Path:    "/refresh",
					Handler: auth.RefreshTokenHandler(serverCtx),
				},
				{
					// 注册账号
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// 发送验证码
					Method:  http.MethodPost,
					Path:    "/send_code",
					Handler: auth.SendVerificationCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 查询某天支出明细
					Method:  http.MethodGet,
					Path:    "/by_date",
					Handler: expense.ExpenseByDateHandler(serverCtx),
				},
				{
					// 支出分类列表
					Method:  http.MethodGet,
					Path:    "/categories",
					Handler: expense.ListExpenseCategoryHandler(serverCtx),
				},
				{
					// 创建自定义分类
					Method:  http.MethodPost,
					Path:    "/category/create",
					Handler: expense.CreateExpenseCategoryHandler(serverCtx),
				},
				{
					// 删除自定义分类
					Method:  http.MethodPost,
					Path:    "/category/delete",
					Handler: expense.DeleteExpenseCategoryHandler(serverCtx),
				},
				{
					// 记录支出
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: expense.CreateExpenseLogHandler(serverCtx),
				},
				{
					// 删除支出记录
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: expense.DeleteExpenseLogHandler(serverCtx),
				},
				{
					// 支出记录列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: expense.ListExpenseLogHandler(serverCtx),
				},
				{
					// 退款
					Method:  http.MethodPost,
					Path:    "/refund",
					Handler: expense.RefundExpenseLogHandler(serverCtx),
				},
				{
					// 分类支出占比
					Method:  http.MethodGet,
					Path:    "/stats/category",
					Handler: expense.ExpenseStatsCategoryHandler(serverCtx),
				},
				{
					// 每月支出趋势
					Method:  http.MethodGet,
					Path:    "/stats/monthly",
					Handler: expense.ExpenseMonthlyTrendHandler(serverCtx),
				},
				{
					// 每日支出趋势
					Method:  http.MethodGet,
					Path:    "/stats/trend",
					Handler: expense.ExpenseStatsTrendHandler(serverCtx),
				},
				{
					// 更新支出记录
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: expense.UpdateExpenseLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/expense"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 按天查询生活记录
					Method:  http.MethodGet,
					Path:    "/by_date",
					Handler: lifelog.LifeLogByDateHandler(serverCtx),
				},
				{
					// 创建生活记录
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: lifelog.CreateLifeLogHandler(serverCtx),
				},
				{
					// 删除生活记录
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: lifelog.DeleteLifeLogHandler(serverCtx),
				},
				{
					// 生活记录列表（游标分页）
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: lifelog.ListLifeLogHandler(serverCtx),
				},
				{
					// 更新生活记录
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: lifelog.UpdateLifeLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/life_log"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 创建总结（用户手动）
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: summary.CreateSummaryHandler(serverCtx),
				},
				{
					// 删除总结
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: summary.DeleteSummaryHandler(serverCtx),
				},
				{
					// AI 生成总结
					Method:  http.MethodPost,
					Path:    "/generate",
					Handler: summary.GenerateAISummaryHandler(serverCtx),
				},
				{
					// 总结列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: summary.ListSummaryHandler(serverCtx),
				},
				{
					// 按时间范围查询总结
					Method:  http.MethodGet,
					Path:    "/range",
					Handler: summary.RangeSummaryHandler(serverCtx),
				},
				{
					// 更新总结
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: summary.UpdateSummaryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/summary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 修改密码
					Method:  http.MethodPost,
					Path:    "/change_password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					// 修改用户信息
					Method:  http.MethodPost,
					Path:    "/update_info",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)
}
