// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/luyb177/life-tracker/backend/internal/handler/auth"
	summary "github.com/luyb177/life-tracker/backend/internal/handler/summary"
	user "github.com/luyb177/life-tracker/backend/internal/handler/user"
	"github.com/luyb177/life-tracker/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 登录账号
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// 刷新令牌
					Method:  http.MethodPost,
					Path:    "/refresh",
					Handler: auth.RefreshTokenHandler(serverCtx),
				},
				{
					// 注册账号
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// 发送验证码
					Method:  http.MethodPost,
					Path:    "/send_code",
					Handler: auth.SendVerificationCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 创建总结（用户手动）
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: summary.CreateSummaryHandler(serverCtx),
				},
				{
					// 删除总结
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: summary.DeleteSummaryHandler(serverCtx),
				},
				{
					// AI 生成总结
					Method:  http.MethodPost,
					Path:    "/generate",
					Handler: summary.GenerateAISummaryHandler(serverCtx),
				},
				{
					// 总结列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: summary.ListSummaryHandler(serverCtx),
				},
				{
					// 更新总结
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: summary.UpdateSummaryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/summary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 修改密码
					Method:  http.MethodPost,
					Path:    "/change_password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					// 修改用户信息
					Method:  http.MethodPost,
					Path:    "/update_info",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)
}
